In [1]:
import pyodbc
import pandas as pd
import numpy as np 
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
## 라이브러리 불러오기
'''메인 라이브러리'''
import numpy as np
import pandas as pd
import os, time, re
import pickle, gzip

'''시각화 관련 라이브러리'''
import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()
import matplotlib as mpl

%matplotlib inline

'''데이터 준비 및 모델 평가 관련 라이브러리'''
from sklearn import preprocessing as pp
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import StratifiedKFold 
from sklearn.metrics import log_loss
from sklearn.metrics import precision_recall_curve, average_precision_score
from sklearn.metrics import roc_curve, auc, roc_auc_score

'''알고리즘 관련 라이브러리'''
import lightgbm as lgb

'''텐서플로 및 케라스 관련 라이브러리'''
import tensorflow as tf
import keras
from keras import backend as K
from keras.models import Sequential, Model
from keras.layers import Activation, Dense, Dropout
from keras.layers import BatchNormalization, Input, Lambda
from keras import regularizers
from keras.losses import mse, binary_crossentropy

from collections import Counter
import numpy as np
import seaborn as sns
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

from collections import Counter

import tensorflow as tf
import tensorflow.keras.layers as layers
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('C://Users/USER/20210906/credit_card/creditcard.csv')

In [2]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve

# 수정된 get_clf_eval() 함수 
def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    # ROC-AUC 추가 
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
    F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))    

In [3]:
#X_train["AMT"].describe()

In [4]:
#X_test["AMT"].describe()

In [5]:
from sklearn.preprocessing import StandardScaler

X = df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test,y_train, y_test= train_test_split(X, y,train_size=0.7, 
                                                    test_size=0.3, random_state=121)

# from imblearn.over_sampling import SMOTE

# smote = SMOTE(random_state=0)
# X_train, y_train = smote.fit_resample(X_train, y_train)
# start_time = time.time()

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# 랜덤 포레스트 학습 및 별도의 테스트 셋으로 예측 성능 평가
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train , y_train)
%time print(rf_clf.fit(X_train , y_train))

pred = rf_clf.predict(X_test)
pred_proba = rf_clf.predict_proba(X_test)[:, 1]

get_clf_eval(y_test , pred, pred_proba)

RandomForestClassifier(random_state=0)
Wall time: 1min 43s
오차 행렬
[[85282     6]
 [   34   121]]
정확도: 0.9995, 정밀도: 0.9528, 재현율: 0.7806,    F1: 0.8582, AUC:0.9436


In [7]:
from sklearn.preprocessing import Normalizer, MinMaxScaler, MaxAbsScaler, RobustScaler

In [8]:
from sklearn.preprocessing import MinMaxScaler

# minmax scaler 선언 및 학습
minmaxScaler = MinMaxScaler().fit(X_train)
%time print(MinMaxScaler().fit(X_train))
# train셋 내 feature들에 대하여 minmax scaling 수행
X_train_minmax = minmaxScaler.transform(X_train) 

# test셋 내 feature들에 대하여 minmax scaling 수행
X_test_minmax = minmaxScaler.transform(X_test) 

MinMaxScaler()
Wall time: 13 ms


In [9]:
# 랜덤 포레스트 학습 및 별도의 테스트 셋으로 예측 성능 평가
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train_minmax , y_train)
pred = rf_clf.predict(X_test_minmax)
accuracy = accuracy_score(y_test , pred)
pred_proba = rf_clf.predict_proba(X_test_minmax)[:, 1]

get_clf_eval(y_test , pred, pred_proba)

오차 행렬
[[85282     6]
 [   34   121]]
정확도: 0.9995, 정밀도: 0.9528, 재현율: 0.7806,    F1: 0.8582, AUC:0.9436


In [10]:
from sklearn.preprocessing import MaxAbsScaler

# MaxAbsScaler 선언 및 학습
maxabsScaler = MaxAbsScaler().fit(X_train)
%time print(MaxAbsScaler().fit(X_train))
# train셋 내 feature들에 대하여 maxabs scaling 수행
X_train_maxabs = maxabsScaler.transform(X_train)

# test셋 내 feature들에 대하여 maxabs scaling 수행
X_test_maxabs = maxabsScaler.transform(X_test)

MaxAbsScaler()
Wall time: 25.9 ms


In [11]:
# 랜덤 포레스트 학습 및 별도의 테스트 셋으로 예측 성능 평가
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train_maxabs , y_train)
pred = rf_clf.predict(X_test_maxabs)
accuracy = accuracy_score(y_test , pred)
pred_proba = rf_clf.predict_proba(X_test_maxabs)[:, 1]

get_clf_eval(y_test , pred, pred_proba)

오차 행렬
[[85282     6]
 [   34   121]]
정확도: 0.9995, 정밀도: 0.9528, 재현율: 0.7806,    F1: 0.8582, AUC:0.9436


In [12]:
from sklearn.preprocessing import StandardScaler

# standard scaler 선언 및 학습
standardScaler = StandardScaler().fit(X_train)
%time print(StandardScaler().fit(X_train))
# train셋 내 feature들에 대하여 standard scaling 수행
X_train_standard = standardScaler.transform(X_train)

# test셋 내 feature들에 대하여 standard scaling 수행
X_test_standard = standardScaler.transform(X_test)

StandardScaler()
Wall time: 85.8 ms


In [13]:
# 랜덤 포레스트 학습 및 별도의 테스트 셋으로 예측 성능 평가
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train_standard , y_train)
pred = rf_clf.predict(X_test_standard)
accuracy = accuracy_score(y_test , pred)
pred_proba = rf_clf.predict_proba(X_test_standard)[:, 1]

get_clf_eval(y_test , pred, pred_proba)

오차 행렬
[[85282     6]
 [   34   121]]
정확도: 0.9995, 정밀도: 0.9528, 재현율: 0.7806,    F1: 0.8582, AUC:0.9436


In [14]:
from sklearn.preprocessing import RobustScaler

# RobustScaler 선언 및 학습
robustScaler = RobustScaler().fit(X_train)
%time print(RobustScaler().fit(X_train))
# train셋 내 feature들에 대하여 robust scaling 수행
X_train_robust = robustScaler.transform(X_train)

# test셋 내 feature들에 대하여 robust scaling 수행
X_test_robust = robustScaler.transform(X_test)

RobustScaler()
Wall time: 145 ms


In [15]:
# 랜덤 포레스트 학습 및 별도의 테스트 셋으로 예측 성능 평가
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train_robust , y_train)
pred = rf_clf.predict(X_test_robust)
accuracy = accuracy_score(y_test , pred)
pred_proba = rf_clf.predict_proba(X_test_robust)[:, 1]

get_clf_eval(y_test , pred, pred_proba)

오차 행렬
[[85282     6]
 [   34   121]]
정확도: 0.9995, 정밀도: 0.9528, 재현율: 0.7806,    F1: 0.8582, AUC:0.9436


In [16]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
%time print(scaler.fit(X_train))
# MaxAbsScaler 선언 및 학습
X_train_normalScaler = scaler.fit_transform(X_train)

X_test_normalScaler = scaler.fit_transform(X_test)

Normalizer()
Wall time: 8.98 ms


In [17]:
# 랜덤 포레스트 학습 및 별도의 테스트 셋으로 예측 성능 평가
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train_normalScaler , y_train)
pred = rf_clf.predict(X_test_normalScaler)
accuracy = accuracy_score(y_test , pred)
pred_proba = rf_clf.predict_proba(X_test_normalScaler)[:, 1]

get_clf_eval(y_test , pred, pred_proba)

오차 행렬
[[85283     5]
 [   41   114]]
정확도: 0.9995, 정밀도: 0.9580, 재현율: 0.7355,    F1: 0.8321, AUC:0.9458
